### ISSUE TITLE
关于 `\tableofcontents` 的目录设置需求

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/cus#11]
我读了一下手册，关于目录定制的地方感觉门槛不低……我没找到类似于 `tocdepth` 的接口，默认只显示三个层级。
```latex
\documentclass{book}
\usepackage{ctex}
\usepackage{cus}
\enablecombinedlist
\setsecnumdepth{4}

\begin{document}

\tableofcontents

\chapter{1}
\section{2}
\subsection{3}
\subsubsection{4}

\end{document}
```

大部分用户可能没有那么强的定制化需求，可能改改层级，然后调一下目录条目的字体，增加引导线啥的。

## 问题
1. `cus` 有提供 `\tableofcontents` 的目录的层级数的调整接口吗？
2. 比如常见的改目录条目字体字号，增加引导线什么的，在 `cus` 宏包下是要仍然像传统那样，用 `tocloft` 宏包来设置就行？

**Comment by Sophanatprime** [comment]
> 1. `cus` 有提供 `\tableofcontents` 的目录的层级数的调整接口吗？

原来可以设置 `tocdepth` 控制目录层级。v0.0.4g 加上了 `\setplaintocdepth` 命令。

> 2. 比如常见的改目录条目字体字号，增加引导线什么的，在 `cus` 宏包下是要仍然像传统那样，用 `tocloft` 宏包来设置就行？

目前还不支持直接控制这些东西，也不支持 `tocloft` 等宏包。
现在比较合适的方法是通过 `\tocsetstyle` 和 `\specifiedtoc` 定义目录，然后提供接口修改。

**Comment by xkwxdyy** [comment]
好的谢谢，希望后续手册中可以多一些目录设置的例子。

**Comment by Sophanatprime** [comment]
v0.0.4h https://github.com/Sophanatprime/cus/commit/763cdd7d9eb2b6f357fca6700e71b20a0346d5e7 新增了 `\templatetoc` 等“模板格式的目录”，能够进行一定程度的定制，但也不至于像 specified 格式的目录那么繁琐。

**Comment by xkwxdyy** [comment]
之前看到仓库里有 example 了，日后我学习一下。感谢。
