### ISSUE TITLE
能否实现 setuptitle once 的效果？

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/cus#12]
我一开始看到 `\setuponetitle` 命令，以为是 setup once 的含义，类似于 `AddToNextHook` 的效果，只作用于下面第一个出现的 title level。
但测试了才发现是 <title level> 只有一个的意思。

不知道能否实现 `\setuptitleonce` 的效果？就是仅仅作用于后面出现的第一个 title level，然后第二个开始就仍然是之前的设置。

**Comment by Sophanatprime** [comment]
增加了 `\setupnexttitle` 命令。
