### ISSUE TITLE
`\CUSDependency{module={...}}` 的失效

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/cus#14]
## 场景
我在一个模块 `acknowledgement` 里新建了一个环境 `acknowledgement`，然后另外一个库里使用 `\CUSDependency{module={acknowledgement}}` 加载，在 `.tex` 文件调用这个库后使用 `acknowledgement` 环境，报错环境未定义。

## 自查
我查看了 `cus.sty` 的关于这部分的源码：
https://github.com/Sophanatprime/cus/blob/f0d8c9c042f5c72a29c1bd012517aee74b235f4a/cus.sty#L332
发现模块的调用设置是空的，这是没来得及写还是我哪里没弄对？

**Comment by Sophanatprime** [comment]
原本的设想是模块只由 `cus` 提供，其它用户定义的内容都使用库，而 `cus` 会自己加载所有模块，所以 `module` 是不需要的。

**Comment by xkwxdyy** [comment]
原来是这样。但是比如一些模块，参考文献、字体啥的您还没写好。论文模板里很多设置可能也只限于论文自用，可能普适性比较小，所以单独建立了一些模块。

**Comment by Sophanatprime** [comment]
用户定义的内容还是使用库比较好。定义库可定制性更强一点，可以使用 `\CUSLibraryDelayedUntil` `\CUSPassOptionsToLibrary` 等等，未来 `\CUSDenpency` 也会为库增加其它功能。
