### ISSUE TITLE
`\backgroundpicture` 如何调整透明度

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/cus#52]
一种办法是不用这个命令，直接用 `\background`，这样就可以用 `\transparent` 来调整透明度
```latex
\background+(lb)[./watermark]{\transparent{0.2}\includegraphics[width = 20cm]{background.png}}
```

但是 `\backgroundpicture` 的话，接口也是 `includegraphics` 的，好像没有 `opacity` 类似的命令，那要如何实现透明度调整呢

**Comment by Sophanatprime** [comment]
不能。`\backgroundpicture` 是简单的封装，只有基础功能。更复杂的需要直接使用 `\background`，或者自定义命令。

**Comment by xkwxdyy** [comment]
好的，感谢
