### ISSUE TITLE
`\background` 如何实现 `rm` 的位置？

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/cus#54]
手册上：
> 水平位置包括:左(l)、右(r)、内侧(i)、外侧(o);垂直 位置包括:顶部(t)、底部(b);它们的组合也就是 layout 的四个角。此外 还有一个 cm，它表示 layout 的正中心，这也是默认值

我试了一下好像 `lm` `rm` 这种不行，为什么不把 `c` 和 `m` 也放入可选中呢？

主要需求是想实现这样的 logo
![image](https://github.com/Sophanatprime/cus/assets/87134063/52134bd5-767e-4e74-a841-5ad184c87bb9)

就是放在页面的左侧或者右侧，只出现一半。

**Comment by Sophanatprime** [comment]
加括号，或者直接用 `text opacity=0.2`，如果是 XeLaTeX 还需要 `\DocumentMetadata{}`：
```tex
\background+(tikz)[./logo]{
  % \put(6cm, -7cm){\transparent{0.2}\includegraphics[width = 5cm]{logo-black}}
  \node at (text.east) {{\transparent{0.2}\includegraphics[height = \textheight]{logo-black}}};
}
```

**Comment by Sophanatprime** [comment]
直接用 `\ifodd\c@page` 判断就可以了，它们总是能获得正确的值。
```tex
\def\oddbackground{..}
\def\evenbackground{..}
\background{\ifodd\c@page \oddbackground\else \evenbackground\fi}
```

**Comment by xkwxdyy** [comment]
> 直接用 `\ifodd\c@page` 判断就可以了，它们总是能获得正确的值。

好的，感谢
