### ISSUE TITLE
编译文档的时候提示找不到 `TH-Times` 字体

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/cus#6]
在 https://github.com/Sophanatprime/cus/commit/814e49c70fbd636cc4173d580b7da3612716c655 后，文档编译基本没问题，除了提示找不到 `TH-Times` 字体。

我找到了代码的源位置： https://github.com/Sophanatprime/cus/blob/814e49c70fbd636cc4173d580b7da3612716c655/cus-cn.tex#L4565
和  https://github.com/Sophanatprime/cus/blob/814e49c70fbd636cc4173d580b7da3612716c655/cus-cn.tex#L4588
将它们注释掉之后编译正常了。

我并没有 Google 到这个 `TH-Times` 字体，请问是您自己开发的？

**Comment by Sophanatprime** [comment]
这是[天珩字库](http://cheonhyeong.com/Simplified/download.html)的字体，TH-Times 的[下载链接](http://cheonhyeong.com/File/TH-Tshyn-4.1.0.7z)在表格的第一行里。

文档中的这个例子用 TH-Times 显示效果比较好。或许可以检查 TH-Times 是否存在再加载。

**Comment by xkwxdyy** [comment]
了解了，谢谢
